pipeline {
                branch 'production'
            }
            steps {
                sh './jenkins/scripts/deploy.sh'
                sh './jenkins/scripts/deploy-for-production.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }